### ISSUE TITLE
Plugin 1.0.3 with Craft 3.1.15 is broken

### ISSUE THREAD

**Issue by jasonschock** [nystudio107/craft-emptycoalesce#4]
Using plugin v 1.0.3. My `composer.json`:

```json
  "require": {
    "php": ">=7.0.0",
    "craftcms/cms": "3.1.15",
    "vlucas/phpdotenv": "^2.4.0",
    "craftcms/aws-s3": "^1.0",
    "craftcms/redactor": "^2.3.2",
    "verbb/super-table": "^2.1.12",
    "dolphiq/redirect": "^1.0.16",
    "fortrabbit/craft-auto-migrate": "^1.1",
    "nystudio107/craft-emptycoalesce": "^1.0"
  },
```

Result:
```
yii\base\ErrorException: Declaration of craft\web\twig\Environment::compileSource(Twig_Source $source) should be compatible with Twig\Environment::compileSource(Twig\Source $source) in /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/twig/Environment.php:0
Stack trace:
#0 /home/vagrant/sites/craft-mbari/vendor/composer/ClassLoader.php(322): ::Composer\Autoload\includeFile()
#1 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/View.php(257): Composer\Autoload\ClassLoader->loadClass()
#2 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/View.php(257): ::spl_autoload_call()
#3 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/View.php(246): craft\web\View->createTwig()
#4 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/View.php(337): craft\web\View->getTwig()
#5 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate()
#6 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate()
#7 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\controllers\TemplatesController->renderTemplate()
#8 /home/vagrant/sites/craft-mbari/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\TemplatesController->actionRender()
#9 /home/vagrant/sites/craft-mbari/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/home/vagrant/sites/craft-mbari/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#10 /home/vagrant/sites/craft-mbari/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#11 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/Controller.php(109): craft\controllers\TemplatesController->runAction()
#12 /home/vagrant/sites/craft-mbari/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\TemplatesController->runAction()
#13 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/Application.php(297): craft\web\Application->runAction()
#14 /home/vagrant/sites/craft-mbari/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#15 /home/vagrant/sites/craft-mbari/vendor/craftcms/cms/src/web/Application.php(286): craft\web\Application->handleRequest()
#16 /home/vagrant/sites/craft-mbari/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#17 /home/vagrant/sites/craft-mbari/web/index.php(21): craft\web\Application->run()
#18 {main}
```

* Removing the plugin fixes the problem.
* Upgrading to Craft 3.1.18 fixes the problem.

Easy enough for us to fix but though I'd report.

**Comment by khalwat** [comment]
So the actual issue here is that you need to clear your caches template caches.

It's not an issue with Craft or with Empty Coalesce.

I do appreciate the bug report tho!
